### ISSUE TITLE
Issue Transpiling main.scss

### ISSUE THREAD

**Issue by hyndsite** [surveyjs/editor#68]
When running the webpack build, it dies when it attempts to transpile the /src/main.scss sass file with the following error - any suggestions?

I have tried it with both node 5.9.1, 6.9.2 and the same versions of npm packages dictated in the project's package.json

```
ERROR in ./~/style-loader/addStyles.js
Module not found: Error: Can't resolve './fixUrls' in 'C:\surveyjseditor\node_modules\style-loader'
resolve './fixUrls' in 'C:\surveyjseditor\node_modules\style-loader'
  using description file: C:\surveyjseditor\node_modules\style-loader\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\surveyjseditor\node_modules\style-loader\package.json (relative path: .)
    using description file: C:\surveyjseditor\node_modules\style-loader\package.json (relative path: ./fixUrls)
      as directory
        C:\surveyjseditor\node_modules\style-loader\fixUrls doesn't exist
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\surveyjseditor\node_modules\style-loader\fixUrls doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\surveyjseditor\node_modules\style-loader\fixUrls.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        C:\surveyjseditor\node_modules\style-loader\fixUrls.tsx doesn't exist
      .scss
        Field 'browser' doesn't contain a valid alias configuration
        C:\surveyjseditor\node_modules\style-loader\fixUrls.scss doesn't exist
[C:\surveyjseditor\node_modules\style-loader\fixUrls]
[C:\surveyjseditor\node_modules\style-loader\fixUrls]
[C:\surveyjseditor\node_modules\style-loader\fixUrls.ts]
[C:\surveyjseditor\node_modules\style-loader\fixUrls.tsx]
[C:\surveyjseditor\node_modules\style-loader\fixUrls.scss]
 @ ./~/style-loader/addStyles.js 35:11-31
 @ ./src/main.scss
 @ ./src/entries/index.ts

ERROR in ./~/css-loader/lib/css-base.js
Module build failed: TypeError: Cannot read property '__esModule' of undefined
    at Function.normalisePlugin (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:142:20)
    at C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\surveyjseditor\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\surveyjseditor\node_modules\babel-loader\lib\index.js:46:20)
    at Object.module.exports (C:\surveyjseditor\node_modules\babel-loader\lib\index.js:163:20)
 @ ./~/css-loader!./~/sass-loader/lib/loader.js!./src/main.scss 1:27-80
 @ ./src/main.scss
 @ ./src/entries/index.ts

ERROR in ./src/main.scss
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property '__esModule' of undefined
    at Function.normalisePlugin (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:142:20)
    at C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\surveyjseditor\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\surveyjseditor\node_modules\babel-loader\lib\index.js:46:20)
    at Object.module.exports (C:\surveyjseditor\node_modules\babel-loader\lib\index.js:163:20)
    at C:\surveyjseditor\node_modules\webpack\lib\NormalModule.js:192:19
    at C:\surveyjseditor\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\surveyjseditor\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at runSyncOrAsync (C:\surveyjseditor\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (C:\surveyjseditor\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at C:\surveyjseditor\node_modules\loader-runner\lib\LoaderRunner.js:202:4
    at C:\surveyjseditor\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:62:14
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)

ERROR in C:\surveyjseditor\node_modules\extract-text-webpack-plugin\loader.js??ref--2-0!C:\surveyjseditor\node_modules\style-loader\index.js!C:\surveyjseditor\node_modules\css-loader\index.js!C:\surveyjseditor\node_modules\sass-loader\lib\loader.js!C:\surveyjseditor\src\main.scss
doesn't export content
Child extract-text-webpack-plugin:
       [0] ./src/fonts/icomoon.eot?sbpmys 74 bytes {0} [built]
           [] -> factory:4ms building:4ms = 8ms
       [1] ./~/css-loader/lib/css-base.js 1.58 kB {0} [built] [failed] [1 error]
           [] -> factory:4ms building:4ms = 8ms
       [2] ./src/fonts/icomoon.svg?sbpmys 74 bytes {0} [built]
           [] -> factory:4ms building:4ms = 8ms
       [3] ./src/fonts/icomoon.ttf?sbpmys 74 bytes {0} [built]
           [] -> factory:4ms building:4ms = 8ms
       [4] ./src/fonts/icomoon.woff?sbpmys 75 bytes {0} [built]
           [] -> factory:4ms building:4ms = 8ms
       [5] ./~/css-loader!./~/sass-loader/lib/loader.js!./src/main.scss 11.7 kB {0} [built]
            factory:13ms building:79ms = 92ms

    ERROR in ./~/css-loader/lib/css-base.js
    Module build failed: TypeError: Cannot read property '__esModule' of undefined
        at Function.normalisePlugin (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:142:20)
        at C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
        at Array.map (native)
        at Function.normalisePlugins (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
        at OptionManager.mergeOptions (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
        at OptionManager.init (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
        at File.initOptions (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\index.js:212:65)
        at new File (C:\surveyjseditor\node_modules\babel-core\lib\transformation\file\index.js:135:24)
        at Pipeline.transform (C:\surveyjseditor\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
        at transpile (C:\surveyjseditor\node_modules\babel-loader\lib\index.js:46:20)
        at Object.module.exports (C:\surveyjseditor\node_modules\babel-loader\lib\index.js:163:20)
     @ ./~/css-loader!./~/sass-loader/lib/loader.js!./src/main.scss 1:27-80
```

**Comment by tsv2013** [comment]
Probably the problem is in some dev dependency. I've locked dependencies versions, and project is building ok on my machine as well as on TravisCI.
@hyndsite Could you please pull latest version from repo, remove "node-modules" folder, reinstall npm modules (via "npm i" command) and try to rebuild?
